In [44]:
import numpy as np
A = np.array([[0,1],[2,3],[4,5]])
B = np.array([[0,1,2,3],[4,5,6,7]])
AB = np.dot(A,B)
print(AB)
print(np.sum(AB, axis=1))

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
[ 22  78 134]
